In [2]:
#Dependencies
import pandas as pd
import numpy as np
import warnings
import datetime as dt
warnings.filterwarnings('ignore')
from sqlalchemy import create_engine, Column, Integer, String, Float, Date

In [3]:
bouts = pd.read_csv("bouts.csv", index_col = 0)
bouts.head()

,event_date,event_name,fighter1,fighter2,pass_stat_f1,pass_stat_f2,round_,str_stat_f1,str_stat_f2,sub_stat_f1,sub_stat_f2,td_stat_f1,td_stat_f2,time,weight_class,win_method_finish,win_method_type,winner
event_attendance,,,,,,,,,,,,,,,,,,
17794,August 04 2018,UFC 227: Dillashaw vs. Garbrandt 2,TJ Dillashaw,Cody Garbrandt,0,0,1,45,17,0,0,0,0,4.10,Bantamweight,Punches,KO/TKO,TJ Dillashaw
17794,August 04 2018,UFC 227: Dillashaw vs. Garbrandt 2,Henry Cejudo,Demetrious Johnson,2,0,5,51,81,0,0,3,1,5.00,Flyweight,NaN,S-DEC,Henry Cejudo
17794,August 04 2018,UFC 227: Dillashaw vs. Garbrandt 2,Renato Moicano,Cub Swanson,4,0,1,17,20,1,0,1,0,4.15,Featherweight,Rear Naked Choke,SUB,Renato Moicano
17794,August 04 2018,UFC 227: Dillashaw vs. Garbrandt 2,JJ Aldrich,Polyana Viana,1,1,3,40,46,0,0,0,1,5.00,Women's Strawweight,NaN,U-DEC,JJ Aldrich
17794,August 04 2018,UFC 227: Dillashaw vs. Garbrandt 2,Thiago Santos,Kevin Holland,8,2,3,69,31,1,1,3,0,5.00,Middleweight,NaN,U-DEC,Thiago Santos

In [4]:
fights = pd.read_csv("fights.csv", index_col = 0)
fights.head()

,fighter_name,fighter_record,height,reach,sapm,slpm,stance,strike_acc,strike_def,sub_avg,td_acc,td_avg,td_def,weight
date_of_birth,,,,,,,,,,,,,,
Jun 01 1991,Sarah Alpar,Record: 8-4-0,"5' 4""",NaN,3.79,4.42,Southpaw,61,40.0,1.9,66,3.79,100,135.0
--,Rico Altamirano,Record: 3-2-0,"5' 10""",NaN,0.00,0.00,NaN,0,0.0,0.0,0,0.00,0,170.0
--,Ben Earwood,Record: 12-3-0,"5' 8""",NaN,0.20,0.50,Orthodox,55,33.0,0.0,100,3.00,0,170.0
--,Eddy Ellis,Record: 16-15-1 (1 NC),"5' 9""",NaN,1.53,3.40,Orthodox,69,68.0,2.0,66,4.00,50,170.0
Nov 13 1980,John Hosman,Record: 18-8-1,"5' 10""",NaN,1.52,1.11,Southpaw,38,45.0,0.0,0,0.00,46,135.0

In [8]:
fights.fillna(value=0,inplace=True)
bouts.fillna(value=0,inplace=True)
bouts

,event_date,event_name,fighter1,fighter2,pass_stat_f1,pass_stat_f2,round_,str_stat_f1,str_stat_f2,sub_stat_f1,sub_stat_f2,td_stat_f1,td_stat_f2,time,weight_class,win_method_finish,win_method_type,winner
event_attendance,,,,,,,,,,,,,,,,,,
17794,August 04 2018,UFC 227: Dillashaw vs. Garbrandt 2,TJ Dillashaw,Cody Garbrandt,0,0,1,45,17,0,0,0,0,4.10,Bantamweight,Punches,KO/TKO,TJ Dillashaw
17794,August 04 2018,UFC 227: Dillashaw vs. Garbrandt 2,Henry Cejudo,Demetrious Johnson,2,0,5,51,81,0,0,3,1,5.00,Flyweight,0,S-DEC,Henry Cejudo
17794,August 04 2018,UFC 227: Dillashaw vs. Garbrandt 2,Renato Moicano,Cub Swanson,4,0,1,17,20,1,0,1,0,4.15,Featherweight,Rear Naked Choke,SUB,Renato Moicano
17794,August 04 2018,UFC 227: Dillashaw vs. Garbrandt 2,JJ Aldrich,Polyana Viana,1,1,3,40,46,0,0,0,1,5.00,Women's Strawweight,0,U-DEC,JJ Aldrich
17794,August 04 2018,UFC 227: Dillashaw vs. Garbrandt 2,Thiago Santos,Kevin Holland,8,2,3,69,31,1,1,3,0,5.00,Middleweight,0,U-DEC,Thiago Santos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14073,September 08 2018,UFC 228: Woodley vs. Till,Darren Stewart,Charles Byrd,0,0,2,24,38,0,0,0,0,2.17,Middleweight,Elbow,KO/TKO,Darren Stewart
14073,September 08 2018,UFC 228: Woodley vs. Till,Diego Sanchez,Craig White,5,0,3,46,18,0,1,3,0,5.00,Welterweight,0,U-DEC,Diego Sanchez
14073,September 08 2018,UFC 228: Woodley vs. Till,Jim Miller,Alex White,2,0,1,15,5,1,0,1,0,1.29,Lightweight,Rear Naked Choke,SUB,Jim Miller
14073,September 08 2018,UFC 228: Woodley vs. Till,Irene Aldana,Lucie Pudilova,0,0,3,119,105,0,0,0,0,5.00,Women's Bantamweight,0,S-DEC,Irene Aldana
14073,September 08 2018,UFC 228: Woodley vs. Till,Jarred Brooks,Roberto Sanchez,1,0,3,24,16,1,0,2,1,5.00,Flyweight,0,S-DEC,Jarred Brooks

In [11]:
drop_bouts = bouts.drop(['round_','time','win_method_finish','win_method_type','weight_class', 'event_name'],axis=1)
drop_bouts

,event_date,fighter1,fighter2,pass_stat_f1,pass_stat_f2,str_stat_f1,str_stat_f2,sub_stat_f1,sub_stat_f2,td_stat_f1,td_stat_f2,winner
event_attendance,,,,,,,,,,,,
17794,August 04 2018,TJ Dillashaw,Cody Garbrandt,0,0,45,17,0,0,0,0,TJ Dillashaw
17794,August 04 2018,Henry Cejudo,Demetrious Johnson,2,0,51,81,0,0,3,1,Henry Cejudo
17794,August 04 2018,Renato Moicano,Cub Swanson,4,0,17,20,1,0,1,0,Renato Moicano
17794,August 04 2018,JJ Aldrich,Polyana Viana,1,1,40,46,0,0,0,1,JJ Aldrich
17794,August 04 2018,Thiago Santos,Kevin Holland,8,2,69,31,1,1,3,0,Thiago Santos
...,...,...,...,...,...,...,...,...,...,...,...,...
14073,September 08 2018,Darren Stewart,Charles Byrd,0,0,24,38,0,0,0,0,Darren Stewart
14073,September 08 2018,Diego Sanchez,Craig White,5,0,46,18,0,1,3,0,Diego Sanchez
14073,September 08 2018,Jim Miller,Alex White,2,0,15,5,1,0,1,0,Jim Miller
14073,September 08 2018,Irene Aldana,Lucie Pudilova,0,0,119,105,0,0,0,0,Irene Aldana
14073,September 08 2018,Jarred Brooks,Roberto Sanchez,1,0,24,16,1,0,2,1,Jarred Brooks

In [23]:
# drop_bouts.set_index('event_date', inplace=True)
drop_bouts.head()

,fighter1,fighter2,pass_stat_f1,pass_stat_f2,str_stat_f1,str_stat_f2,sub_stat_f1,sub_stat_f2,td_stat_f1,td_stat_f2,winner
event_date,,,,,,,,,,,
August 04 2018,TJ Dillashaw,Cody Garbrandt,0,0,45,17,0,0,0,0,TJ Dillashaw
August 04 2018,Henry Cejudo,Demetrious Johnson,2,0,51,81,0,0,3,1,Henry Cejudo
August 04 2018,Renato Moicano,Cub Swanson,4,0,17,20,1,0,1,0,Renato Moicano
August 04 2018,JJ Aldrich,Polyana Viana,1,1,40,46,0,0,0,1,JJ Aldrich
August 04 2018,Thiago Santos,Kevin Holland,8,2,69,31,1,1,3,0,Thiago Santos

In [30]:
# Exported file as a new csv
drop_bouts.to_csv("cleaned_bouts.csv")

In [32]:
new_bouts = pd.read_csv("cleaned_bouts.csv")
new_bouts

,event_date,fighter1,fighter2,pass_stat_f1,pass_stat_f2,str_stat_f1,str_stat_f2,sub_stat_f1,sub_stat_f2,td_stat_f1,td_stat_f2,winner
0,August 04 2018,TJ Dillashaw,Cody Garbrandt,0,0,45,17,0,0,0,0,TJ Dillashaw
1,August 04 2018,Henry Cejudo,Demetrious Johnson,2,0,51,81,0,0,3,1,Henry Cejudo
2,August 04 2018,Renato Moicano,Cub Swanson,4,0,17,20,1,0,1,0,Renato Moicano
3,August 04 2018,JJ Aldrich,Polyana Viana,1,1,40,46,0,0,0,1,JJ Aldrich
4,August 04 2018,Thiago Santos,Kevin Holland,8,2,69,31,1,1,3,0,Thiago Santos
...,...,...,...,...,...,...,...,...,...,...,...,...
5241,September 08 2018,Darren Stewart,Charles Byrd,0,0,24,38,0,0,0,0,Darren Stewart
5242,September 08 2018,Diego Sanchez,Craig White,5,0,46,18,0,1,3,0,Diego Sanchez
5243,September 08 2018,Jim Miller,Alex White,2,0,15,5,1,0,1,0,Jim Miller
5244,September 08 2018,Irene Aldana,Lucie Pudilova,0,0,119,105,0,0,0,0,Irene Aldana
5245,September 08 2018,Jarred Brooks,Roberto Sanchez,1,0,24,16,1,0,2,1,Jarred Brooks

In [38]:
# connected to postgres
username = 'postgres'
password = 'x'
# connected to database created in postgres
database = 'ufc_db'
engine = create_engine(f'postgresql://{username}:{password}@localhost/{database}')
connection = engine.connect()

In [39]:
# read csv file in table created in postgres
new_bouts = new_bouts.to_sql('bouts', con=connection, if_exists='append', index=False, method='multi', chunksize=5000)

In [40]:
# read csv file in table created in postgres
new_fighters = fights.to_sql('fighters', con=connection, if_exists='append', index=False, method='multi', chunksize=5000)

In [41]:
# closed the connection
connection.close()